### ISSUE TITLE
Request to include KOKKOS accelerator package in DeePMD Lammps library

### ISSUE THREAD

**Issue by skethirajan** [deepmd-kit-recipes/lammps-dp-feedstock#64]
I have been actively using DeePMD-kit package in my research. I want to run Lammps with GPUs. The Lammps executable shipped with DeePMD (GPU version) from conda channel is built without any accelerators (GPU). I request to include KOKKOS accelerator package additionally.

**Comment by njzjz** [comment]
We've decided to deprecate the official deepmodeling conda channel. Future releases will use conda-forge packages directly, i.e. https://github.com/conda-forge/lammps-feedstock
